# The display name for the workflow shown in the GitHub Actions tab.
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Specifies the type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repo under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Checkout repository
        run: bash ci/check_repo.sh